//! Interference structures

use crate::{EdgeId, FaceId, SectionCurveId, VertexId};
use truck_base::cgmath64::Point2;

/// Vertex-vertex interference
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VVInterference {
    /// First vertex
    pub vertex1: VertexId,
    /// Second vertex
    pub vertex2: VertexId,
}

/// Vertex-edge interference
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct VEInterference {
    /// Vertex
    pub vertex: VertexId,
    /// Edge
    pub edge: EdgeId,
    /// Parameter on edge
    pub parameter: f64,
}

/// Vertex-face interference
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct VFInterference {
    /// Vertex
    pub vertex: VertexId,
    /// Face
    pub face: FaceId,
    /// Parameters on face surface
    pub parameters: (f64, f64),
}

/// Edge-edge interference
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EEInterference {
    /// First edge
    pub edge1: EdgeId,
    /// Second edge
    pub edge2: EdgeId,
    /// Parameter on the first edge curve
    pub t_a: f64,
    /// Parameter on the second edge curve
    pub t_b: f64,
}

/// Edge-face interference
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EFInterference {
    /// Edge
    pub edge: EdgeId,
    /// Face
    pub face: FaceId,
    /// Parameter on edge curve
    pub parameter: f64,
    /// Parameters on face surface
    pub surface_parameters: (f64, f64),
}

/// Face-face interference
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FFInterference {
    /// First face
    pub face1: FaceId,
    /// Second face
    pub face2: FaceId,
    /// Generated section curve
    pub section_curve: SectionCurveId,
}

/// A section curve generated by a face-face intersection.
#[derive(Debug, Clone, PartialEq)]
pub struct SectionCurve {
    /// Curve identifier.
    pub id: SectionCurveId,
    /// The two source faces.
    pub faces: (FaceId, FaceId),
    /// First endpoint on the section, if open.
    pub start: VertexId,
    /// Second endpoint on the section, if open.
    pub end: VertexId,
    /// Polyline samples describing the section in model space.
    pub samples: Vec<truck_base::cgmath64::Point3>,
    /// Polyline samples of the section projected into each source face's parameter space.
    pub face_parameters: [(FaceId, Vec<Point2>); 2],
}

/// Interference table
#[derive(Debug, Default)]
pub struct InterferenceTable {
    /// Vertex-vertex interferences
    pub vv: Vec<VVInterference>,
    /// Vertex-edge interferences
    pub ve: Vec<VEInterference>,
    /// Vertex-face interferences
    pub vf: Vec<VFInterference>,
    /// Edge-edge interferences
    pub ee: Vec<EEInterference>,
    /// Edge-face interferences
    pub ef: Vec<EFInterference>,
    /// Face-face interferences
    pub ff: Vec<FFInterference>,
    /// Section curves generated by face-face intersections.
    pub section_curves: Vec<SectionCurve>,
}

impl InterferenceTable {
    /// Store a vertex-vertex interference.
    pub fn push_vv(&mut self, interference: VVInterference) {
        self.vv.push(interference);
    }

    /// Store a vertex-edge interference.
    pub fn push_ve(&mut self, interference: VEInterference) {
        self.ve.push(interference);
    }

    /// Store a vertex-face interference.
    pub fn push_vf(&mut self, interference: VFInterference) {
        self.vf.push(interference);
    }

    /// Store an edge-edge interference.
    pub fn push_ee(&mut self, interference: EEInterference) {
        self.ee.push(interference);
    }

    /// Store an edge-face interference.
    pub fn push_ef(&mut self, interference: EFInterference) {
        self.ef.push(interference);
    }

    /// Store a face-face interference.
    pub fn push_ff(&mut self, interference: FFInterference) {
        self.ff.push(interference);
    }

    /// Store a section curve.
    pub fn push_section_curve(&mut self, section_curve: SectionCurve) {
        self.section_curves.push(section_curve);
    }

    /// Borrow all vertex-vertex interferences.
    pub fn vv(&self) -> &[VVInterference] {
        &self.vv
    }

    /// Borrow all vertex-edge interferences.
    pub fn ve(&self) -> &[VEInterference] {
        &self.ve
    }

    /// Borrow all vertex-face interferences.
    pub fn vf(&self) -> &[VFInterference] {
        &self.vf
    }

    /// Borrow all edge-edge interferences.
    pub fn ee(&self) -> &[EEInterference] {
        &self.ee
    }

    /// Borrow all edge-face interferences.
    pub fn ef(&self) -> &[EFInterference] {
        &self.ef
    }

    /// Borrow all face-face interferences.
    pub fn ff(&self) -> &[FFInterference] {
        &self.ff
    }

    /// Borrow all section curves.
    pub fn section_curves(&self) -> &[SectionCurve] {
        &self.section_curves
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stores_vv_interference_records() {
        let mut table = InterferenceTable::default();
        let interference = VVInterference { vertex1: VertexId(1), vertex2: VertexId(2) };

        table.push_vv(interference);

        assert_eq!(table.vv(), &[interference]);
    }

    #[test]
    fn stores_ve_interference_records() {
        let mut table = InterferenceTable::default();
        let interference = VEInterference {
            vertex: VertexId(1),
            edge: EdgeId(2),
            parameter: 0.25,
        };

        table.push_ve(interference);

        assert_eq!(table.ve(), &[interference]);
    }

    #[test]
    fn stores_vf_interference_records() {
        let mut table = InterferenceTable::default();
        let interference = VFInterference {
            vertex: VertexId(1),
            face: FaceId(2),
            parameters: (0.25, 0.75),
        };

        table.push_vf(interference);

        assert_eq!(table.vf(), &[interference]);
    }

    #[test]
    fn stores_ee_interference_records() {
        let mut table = InterferenceTable::default();
        let interference = EEInterference {
            edge1: EdgeId(1),
            edge2: EdgeId(2),
            t_a: 0.25,
            t_b: 0.75,
        };

        table.push_ee(interference);

        assert_eq!(table.ee(), &[interference]);
    }

    #[test]
    fn stores_ef_interference_records() {
        let mut table = InterferenceTable::default();
        let interference = EFInterference {
            edge: EdgeId(1),
            face: FaceId(2),
            parameter: 0.25,
            surface_parameters: (0.25, 0.75),
        };

        table.push_ef(interference);

        assert_eq!(table.ef(), &[interference]);
    }

    #[test]
    fn stores_ff_interference_and_section_curve_records() {
        let mut table = InterferenceTable::default();
        let section_curve = SectionCurve {
            id: SectionCurveId(3),
            faces: (FaceId(1), FaceId(2)),
            start: VertexId(4),
            end: VertexId(5),
            samples: vec![truck_base::cgmath64::Point3::new(0.0, 0.0, 0.0)],
            face_parameters: [
                (FaceId(1), vec![Point2::new(0.0, 0.0)]),
                (FaceId(2), vec![Point2::new(1.0, 1.0)]),
            ],
        };
        let interference = FFInterference {
            face1: FaceId(1),
            face2: FaceId(2),
            section_curve: SectionCurveId(3),
        };

        table.push_section_curve(section_curve.clone());
        table.push_ff(interference);

        assert_eq!(table.section_curves(), &[section_curve]);
        assert_eq!(table.ff(), &[interference]);
    }
}
